module.exports = {
  apps: [
    { name: 'lobby', script: '/home/boshin57/Tobmate_Live/dist/lobby.js', cwd: '/home/boshin57/Tobmate_Live', env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', GO_ROOM_SERVER_HOST: 'tobmate.com', PUZZLE_ROOM_SERVER_HOST: 'tobmate.com', PDESIGN_ROOM_SERVER_HOST: 'tobmate.com', FFA_ROOM_SERVER_HOST: 'tobmate.com', SKPNI_ROOM_SERVER_HOST: 'tobmate.com', NINROW_ROOM_SERVER_HOST: 'tobmate.com', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_SOCKET_PORT: '8002', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_GO_ROOM_SOCKET_PORT: '8004', TOBMATE_GO_ROOM_WEB_PORT: '8005', TOBMATE_PUZZLE_ROOM_SOCKET_PORT: '8006', TOBMATE_PUZZLE_ROOM_WEB_PORT: '8007', TOBMATE_PDESIGN_ROOM_SOCKET_PORT: '8008', TOBMATE_PDESIGN_ROOM_WEB_PORT: '8009', TOBMATE_FFA_ROOM_SOCKET_PORT: '8010', TOBMATE_FFA_ROOM_WEB_PORT: '8011', TOBMATE_SKPNI_ROOM_SOCKET_PORT: '8012', TOBMATE_SKPNI_ROOM_WEB_PORT: '8013', TOBMATE_NINROW_ROOM_SOCKET_PORT: '8014', TOBMATE_NINROW_ROOM_WEB_PORT: '8015' } },
    { name: 'tobmate', script: '/home/boshin57/Tobmate_Live/dist/index.js', cwd: '/home/boshin57/Tobmate_Live', kill_timeout: 10000, env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', MONGODB_URL: 'mongodb://localhost:27017/tob' } },
    { name: 'goroom', script: '/home/boshin57/Tobmate_Live/dist/goRoom.js', cwd: '/home/boshin57/Tobmate_Live', kill_timeout: 10000, env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_GO_ROOM_SOCKET_PORT: '8004', TOBMATE_GO_ROOM_WEB_PORT: '8005' } },
    { name: 'puzzleroom', script: '/home/boshin57/Tobmate_Live/dist/puzzleRoom.js', cwd: '/home/boshin57/Tobmate_Live', env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_PUZZLE_ROOM_SOCKET_PORT: '8006', TOBMATE_PUZZLE_ROOM_WEB_PORT: '8007' } },
    { name: 'pdesignroom', script: '/home/boshin57/Tobmate_Live/dist/pdesignRoom.js', cwd: '/home/boshin57/Tobmate_Live', env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_PDESIGN_ROOM_SOCKET_PORT: '8008', TOBMATE_PDESIGN_ROOM_WEB_PORT: '8009' } },
    { name: 'ffaroom', script: '/home/boshin57/Tobmate_Live/dist/ffaRoom.js', cwd: '/home/boshin57/Tobmate_Live', env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_FFA_ROOM_SOCKET_PORT: '8010', TOBMATE_FFA_ROOM_WEB_PORT: '8011' } },
    { name: 'skoniroom', script: '/home/boshin57/Tobmate_Live/dist/skoniRoom.js', cwd: '/home/boshin57/Tobmate_Live', env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_SKPNI_ROOM_SOCKET_PORT: '8012', TOBMATE_SKPNI_ROOM_WEB_PORT: '8013' } },
    { name: 'ninrowroom', script: '/home/boshin57/Tobmate_Live/dist/ninrowRoom.js', cwd: '/home/boshin57/Tobmate_Live', env: { PROTOCOL: 'http', TOBMATE_HOST: 'tobmate.com', LOBBY_SERVER_HOST: 'localhost', MONGODB_URL: 'mongodb://localhost:27017/tob', TOBMATE_LOBBY_WEB_PORT: '8003', TOBMATE_NINROW_ROOM_SOCKET_PORT: '8014', TOBMATE_NINROW_ROOM_WEB_PORT: '8015' } },
    { name: 'katago', script: '/home/boshin57/Tobmate_Live/dist/katago-middleware.js', cwd: '/home/boshin57/Tobmate_Live', env: { LD_LIBRARY_PATH: '/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/cudnn/lib:/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/cublas/lib:/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/cuda_runtime/lib:/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/curand/lib:/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/cufft/lib:/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/cusolver/lib:/home/boshin57/tob_env/lib/python3.11/site-packages/nvidia/nvjitlink/lib' } }
  ]
}
